version: "3"
services:
  prometheus:
    image: prom/prometheus:v2.46.0
    restart: unless-stopped
    volumes:
      - prometheus_data:/prometheus
      - prometheus_config:/etc/prometheus
    ports:
      - "9090:9090"

  alertmanager:
    image: prom/alertmanager:v0.25.0
    restart: unless-stopped
    ports:
      - "9093:9093"
    volumes:
      - alertmanager_config:/etc/alertmanager
      - alertmanager_data:/alertmanager

  grafana:
    image: grafana/grafana:10.0.5
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - grafana_storage:/var/lib/grafana
volumes:
  prometheus_data:
  prometheus_config:
  alertmanager_config:
  alertmanager_data:
  grafana_storage:
